### ISSUE TITLE
Anbefalede libs

### ISSUE THREAD

**Issue by mortenholmgaard** [izbrannick/Radio#1]
Hey

Jeg ville bare lige anbefale et par libs jeg har stor gavn af at bruge:
Crashlytics fra https://fabric.io - det klart bedst tool til opsamlig af crashes.
Android annotations: http://androidannotations.org/

**Comment by izbrannick** [comment]
Fedt tak :-)
Jeg kigger på det. Lige nu kæmper jeg med at strikke en XML parser, da det
jeg får fra shoutcast er noget rod, fyldt med special characters udenfor
utf-8 encoding.

God påske til dig og din familie

Den tir. 22. mar. 2016 17.04 skrev Morten Holmgaard <
notifications@github.com>:

**Comment by izbrannick** [comment]
H <https://fabric.io/>ej igen.

https://fabric.io er fint mht. feedback på crash reports osv, men det
trækker godt nok tænder ud af appen mht performance, kan de passe?

tir. 22. mar. 2016 kl. 17.08 skrev H.G.Luther <izbrannick@gmail.com>:

**Comment by mortenholmgaard** [comment]
Det tvivler jeg på det gør - jeg har aldrig oplevet performance problemer som jeg kunne kæde sammen med det.

Det er det bedst tool der findes til det og er meget udbredt - Twitter ejer det.

**Comment by izbrannick** [comment]
Det er også ret godt, tak for tippet :-)

Den ons. 23. mar. 2016 15.23 skrev Morten Holmgaard <
notifications@github.com>:

**Comment by izbrannick** [comment]
Tak for dit input. Det bliver brugt flittigt ;) Er i øvrigt også i gang med en iOS app (meget simplere version, da jeg er ikke en haj hverken i Swift eller Xcode ) Men har strikket sammmen en.  Blev lige overrasket over at det koster 799,- om året for at kunne publishe en app??

**Comment by mortenholmgaard** [comment]
Ja det koster det. Jeg har dog adgang til IM/Lohses konto og jeg har også selv en konto, som du evt. kan bruge..
